// Auto-generated by scripts/build-from-curated.py — do not edit manually.
// Regenerate with: python3 scripts/build-from-curated.py
export const MERCADONA_MENU = `# CATÁLOGO MERCADONA
# Formato por línea: Nombre | €/unidad | €/kg-L | kcal/P/C/F per 100g

## Aceite, especias y salsas — Aceite, vinagre y sal
- Vinagre de vino blanco Hacendado | 0.65€ | 0.65€/L | 20/0/0/0
- Vinagre de manzana Hacendado | 0.90€ | 0.90€/L | 17/0/0/0
- Aceite de oliva virgen extra Hacendado | 4.95€ | 4.95€/L | 822/0/0/91.4
- Limón exprimido Hacendado | 1.40€ | 5.00€/L | 29/0/7.1/0
- Vinagre de manzana Hacendado sin filtrar | 2.50€ | 5.00€/L | 16/0/0.3/0
- Aceite de oliva virgen extra Hacendado Gran Selección | 5.95€ | 7.93€/L | 822/0/0/91
- Vinagre de Jerez reserva Hacendado | 2.10€ | 8.40€/L | 37/0/0/0
- Aceite de oliva virgen extra Picual Casa Juncal | 4.85€ | 9.70€/L | 824/0/0/92
- Aceite de coco virgen Hacendado | 5.25€ | 11.67€/L | 884/0/0/100

## Aceite, especias y salsas — Especias
- Cebolla frita crujiente Hacendado | 1.15€ | 7.67€/kg | 590/6/40/44
- Cebolla en polvo Hacendado | 0.94€ | 15.67€/kg | 44/1.3/9.3/0.3
- Ajo y Perejil Hacendado | 1.35€ | 18.24€/kg | 246/11.1/45.4/1.5
- Sazonador pollo y carne Hacendado | 1.40€ | 18.42€/kg | 163/6/21.3/3.1
- Pimentón picante Hacendado | 1.35€ | 22.50€/kg | 263/11/54/2.2
- Sazonador barbacoa Hacendado para pollo y costillas | 1.30€ | 22.81€/kg | 299/3/65.7/1.3
- Piñones Hacendado | 3.25€ | 46.43€/kg | 669/17.3/11/60

## Aceite, especias y salsas — Mostaza
- Mostaza clásica Hacendado | 1.35€ | 3.48€/kg | 75/3.8/2.3/5.3
- Mostaza de Dijon Hacendado | 1.25€ | 6.25€/kg | 149/7.2/1.8/11

## Aceite, especias y salsas — Salsas básicas
- Tomate frito sin azúcares añadidos Hacendado | 1.10€ | 1.97€/kg | 65/1.5/6.5/3.5
- Salsa de Soja Hacendado | 1.20€ | 4.80€/L | 66/7.3/6.3/0.5
- Salsa de Soja sin gluten Hacendado | 2.50€ | 10.00€/L | 57/10/2/0.5
- Salsa Pesto con albahaca Hacendado | 1.95€ | 10.26€/kg | 570/5.9/7.9/57
- Pasta de sésamo Tahini Hacendado | 2.95€ | 14.75€/kg | 710/25/3.2/66

## Aperitivos — Frutos secos y fruta desecada (naturales)
- Cacahuete tostado Hacendado 0% sal añadida | 1.55€ | 3.88€/kg | 595/24.9/10/48
- Cacahuete tostado Hacendado pelado 0% sal añadida | 1.05€ | 5.25€/kg | 617/26/8.8/51
- Pipas girasol naturales Hacendado peladas | 1.15€ | 5.75€/kg | 573/12.5/6.8/51
- Nuez natural Hacendado | 3.70€ | 6.17€/kg | 716/17/2.2/69.6
- Pipas girasol tostadas Hacendado 0% sal añadida | 1.30€ | 6.50€/kg | 636/25.7/5.5/53.7
- Dátiles desecados sin hueso Hacendado | 1.65€ | 6.60€/kg | 296/2.2/68/0.5
- Pasas sultanas sin semillas Hacendado | 1.80€ | 7.20€/kg | 324/3.1/73/1.1
- Mezcla semillas Hacendado | 1.46€ | 7.30€/kg | 567/20/5.7/47
- Ciruelas desecadas sin hueso Hacendado | 2.14€ | 8.56€/kg | 240/2.2/57/0.4
- Pipas de calabaza natural Hacendado peladas | 1.70€ | 11.33€/kg | 67/1.6/14.5/0.7
- Almendra natural Hacendado | 2.30€ | 11.50€/kg | 642/25.2/5.9/54.8
- Nuez natural Hacendado pelada | 2.50€ | 12.50€/kg | 696/6.2/7/69.6
- Anacardo natural Hacendado | 2.70€ | 13.50€/kg | 574/18/7.1/46.5

## Arroz, legumbres y pasta — Arroz
- Arroz largo Hacendado | 1.25€ | 1.25€/kg | 352/6.5/78/0.8
- Arroz redondo Hacendado | 1.30€ | 1.30€/kg | 344/8.2/75/1
- Arroz integral largo Hacendado | 1.65€ | 1.65€/kg | 350/7.6/72/2.8
- Cous cous mediano Hacendado | 1.95€ | 1.95€/kg | 346/12/69/1.6
- Arroz basmati aromático Hacendado | 2.10€ | 2.10€/kg | 355/9/78/0.6
- Quinoa Hacendado | 2.70€ | 5.40€/kg | 389/14/66/6.1

## Arroz, legumbres y pasta — Legumbres
- Lenteja pardina Hacendado | 1.95€ | 1.95€/kg | 320/24.5/48.1/1.2
- Lenteja Hacendado | 2.10€ | 2.10€/kg | 320/24.5/48.1/1.2
- Garbanzo cocido Hacendado | 0.85€ | 2.12€/kg | 90/5.5/9.5/2.2
- Garbanzo Hacendado | 2.20€ | 2.20€/kg | 348/18.6/47.5/6.1
- Lenteja cocida Hacendado | 0.90€ | 2.25€/kg | 89/8.2/10.7/0.4
- Alubia negra Hacendado | 2.50€ | 2.50€/kg | 292/21.4/40.9/1
- Garbanzo lechoso Andaluz Hacendado | 2.50€ | 2.50€/kg | 354/15.9/52/5.3

## Arroz, legumbres y pasta — Pasta
- Macarrón Hacendado | 0.80€ | 1.60€/kg | 361/13/72/1.5
- Spaghetti Hacendado | 0.80€ | 1.60€/kg | 361/13/72/1.5
- Fideuá Hacendado | 0.80€ | 1.60€/kg | 361/13/72/1.5
- Fideo grueso Hacendado | 0.80€ | 1.60€/kg | 361/13/72/1.5
- Pasta penne rigate Hacendado | 0.80€ | 1.60€/kg | 361/13/72/1.5
- Spaghetti integral Hacendado | 1.15€ | 2.30€/kg | 345/13.5/62/2.4
- Macarrón rayado integral Hacendado | 1.15€ | 2.30€/kg | 345/13.5/62/2.4
- Pasta fusilli 100% lentejas rojas Felicia | 1.65€ | 6.60€/kg | 334/25/50/1.7

## Endulzantes naturales
- Miel de flores Hacendado | 4.80€ | 4.80€/kg | 333/0.5/83/0
- Miel de naranjo Hacendado | 4.20€ | 8.40€/kg | 333/0.5/83/0

## Cacao y café
- Cacao puro en polvo La Chocolatera | 4.75€ | 17.93€/kg | 375/25.5/16.3/16
- Café molido natural Hacendado | 4.90€ | 9.80€/kg | 324/17/14/11
- Café en grano natural Hacendado | 6.00€ | 12.00€/kg | 320/16/11/11

## Carne — Aves y pollo
- Cuartos traseros familiar de pollo | 5.02€ | 2.90€/kg | 138/18/0/7.3
- Pollo entero | 6.65€ | 3.50€/kg | 163/19/0/9.5
- Hígados y corazones de pollo | 1.20€ | 4.00€/kg | 120/17/0.6/5.4
- Contramuslos de pollo sin piel | 3.40€ | 4.20€/kg | 129/19/0/5.9
- Pechugas enteras familiar de pollo | 6.84€ | 6.00€/kg | 108/22/0.5/1.8
- Contramuslos de pollo deshuesados y sin piel | 3.58€ | 6.50€/kg | 127/19/1.6/4.9
- Tacos de pavo | 4.16€ | 7.30€/kg | 108/21/0/2.9
- Filetes pechuga de pollo | 4.09€ | 7.30€/kg | 106/22/0/1.8
- Filetes pechuga de pollo extra tiernos | 4.26€ | 7.60€/kg | 108/23.4/0.7/1.3
- Solomillos de pollo | 3.68€ | 8.00€/kg | 106/22/0/1.8
- Filetes de pavo contramuslo | 4.92€ | 8.20€/kg | 124/20/1/5
- Filetes pechuga de pavo | 5.16€ | 8.75€/kg | 103/24/0/0.9

## Carne — Cerdo (cortes magros, sin adobos industriales)
- Lomo de cerdo trozo | 4.80€ | 4.95€/kg | 152/18/0/8.9
- Cerdo a tacos | 3.22€ | 5.75€/kg | 129/23.1/0/3.9
- Secreto de cerdo | 3.04€ | 6.20€/kg | 146/19.1/0.5/7.5
- Filetes lomo de cerdo | 3.37€ | 6.60€/kg | 152/18/0/8.9
- Filetes hígado de cerdo | 3.37€ | 6.60€/kg | 120/21.4/0/3.7
- Solomillo de cerdo | 4.29€ | 7.80€/kg | 131/21/0/5.1
- Carrillada de cerdo | 6.55€ | 13.10€/kg | 146/20.1/0.5/7.3

## Carne — Conejo y cordero
- Conejo entero | 10.41€ | 8.60€/kg | 133/20.2/3/5.7
- Medio conejo troceado | 5.34€ | 8.90€/kg | 131/21/0/5.3
- Filetes hígado de cordero | 4.42€ | 13.00€/kg | 211/24/1.5/12
- Paletillas de conejo | 7.96€ | 19.90€/kg | 157/19/0/9

## Carne — Picada (sin aditivos preparados)
- Preparado de carne picada vacuno | 5.50€ | 11.00€/kg | 190/18/2.4/12
- Preparado de carne picada vacuno extra | 5.40€ | 13.50€/kg | 204/19/0.5/14

## Carne — Vacuno (cortes magros)
- Filetes hígado de vacuno | 4.58€ | 10.40€/kg | 133/21/1.9/4.5
- Tacos de vacuno marinado para guisar | 9.72€ | 16.20€/kg | 93/19/1/1.4
- Escalopín de vacuno añojo para plancha | 7.58€ | 18.50€/kg | 156/22/0.6/7.5
- Filetes de vacuno añojo para plancha | 7.98€ | 19.00€/kg | 129/22/0.5/4.5
- Lomo de vacuno añojo | 7.92€ | 23.50€/kg | 175/21/0.5/10
- Entrecot de vacuno añojo | 6.63€ | 26.50€/kg | 191/22/0.5/12
- Carpaccio de vacuno | 4.10€ | 37.27€/kg | 108/20/2.2/2.9
- Solomillo de vacuno | 11.80€ | 41.40€/kg | 135/22/0.5/5.2

## Cereales — Avena y muesli sin azúcares añadidos
- Copos de avena Brüggen | 1.35€ | 1.69€/kg | 376/11.5/68.5/5.5
- Avena molida Hacendado | 1.15€ | 2.30€/kg | 384/12.2/59.9/7.1
- Cereales copos de maíz Corn Flakes Hacendado 0% azúcares añadidos | 1.50€ | 3.00€/kg | 373/6.7/82/1.7
- Cereales con salvado de trigo Fibra Sticks Hacendado | 1.80€ | 3.60€/kg | 342/16/46/13
- Cereales copos de trigo integral y arroz Hacendado 0% azúcares añadidos | 2.00€ | 4.00€/kg | 373/10.3/75/1.6
- Copos de avena sin gluten Hacendado | 2.10€ | 4.20€/kg | 370/14/58/6.5
- Cereales copos de trigo espelta integral Hacendado 0% azúcares añadidos | 1.70€ | 4.25€/kg | 364/14.6/66/2.7
- Cereales Cereal Mix Hacendado 0% azúcares añadidos | 2.40€ | 6.40€/kg | 372/9.4/74.8/2.7

## Tortitas (las menos procesadas)
- Tortitas de maíz Hacendado | 1.10€ | 9.17€/kg | 368/7.5/80/1.8

## Charcutería — Cocidos magros
- Pechuga de pavo Hacendado finas lonchas | 3.95€ | 9.88€/kg | 117/20.5/0.5/3.4
- Pechuga de pavo reducido en sal Hacendado finas lonchas | 3.95€ | 9.88€/kg | 110/18/1.5/3.5
- Jamón cocido extra Hacendado finas lonchas | 2.00€ | 10.00€/kg | 101/18.6/0.9/2.5
- Pechuga de pavo finas lonchas Hacendado | 2.30€ | 11.50€/kg | 78/17.8/0.6/0.5
- Pechuga de pollo braseada Hacendado finas lonchas | 2.30€ | 11.50€/kg | 84/16.9/1.3/1.2
- Tiras de pechuga pollo al horno Hacendado | 2.25€ | 16.07€/kg | 107/23.4/0.6/1.2
- Tiras de pechuga de pollo al natural Hacendado | 2.25€ | 16.07€/kg | 107/23.4/0.6/1.2
- Pechuguita de pollo 99% La Carloteña asada al horno lonchas | 2.50€ | 20.00€/kg | 125/26.8/0.5/2

## Jamón serrano e ibérico
- Taco jamón curado | 3.85€ | 17.50€/kg | 179/27.9/0.8/7.4
- Jamón serrano lonchas Incarlopsa | 4.10€ | 17.08€/kg | 248/33.5/1/12.2
- Lomo embuchado Hacendado lonchas | 2.55€ | 17.00€/kg | 199/38/0.5/5
- Cabecero de lomo Hacendado lonchas | 2.70€ | 18.00€/kg | 270/31/0.5/16
- Lomo de pavo Hacendado lonchas | 3.20€ | 25.60€/kg | 215/40/0.7/5.8

## Quesos curados, semicurados y tiernos (sin aditivos industriales)
- Queso tierno gouda de vaca Hacendado | 3.30€ | 7.33€/kg | 359/22.6/0/30.2
- Queso tierno bola edam de vaca Holland Corona | 3.60€ | 7.91€/kg | 324/26/0/24
- Queso emmental de vaca Hacendado | 3.00€ | 8.57€/kg | 369/27/0.5/29
- Queso semicurado mezcla Hacendado | 4.14€ | 9.85€/kg | 421/25/1.6/35
- Queso curado mezcla Hacendado | 4.67€ | 11.40€/kg | 431/25/1.8/36
- Queso tierno tronchón mezcla Hacendado | 3.21€ | 12.35€/kg | 366/24.5/1.4/29.2
- Queso viejo de oveja Hacendado | 4.25€ | 13.70€/kg | 447/24/0.5/39
- Queso semicurado de cabra Hacendado | 4.54€ | 15.15€/kg | 419/23.2/2.5/35.1
- Queso grana padano Zanetti | 3.77€ | 16.40€/kg | 398/33/0/29
- Queso añejo de oveja al romero Hacendado | 5.18€ | 19.20€/kg | 434/27/0.5/36

## Quesos frescos y blandos
- Queso fresco batido desnatado 0% MG Hacendado | 1.10€ | 2.20€/kg | 46/8/3.5/0.5
- Queso fresco Burgos natural Hacendado | 2.05€ | 4.10€/kg | 157/11/3.7/10.9
- Requesón mezcla Hacendado | 1.00€ | 5.00€/kg | 139/9.9/2.2/10
- Queso fresco de vaca Hacendado | 1.60€ | 6.40€/kg | 168/11.8/4.5/11.4
- Mozzarella fresca de vaca Hacendado | 0.90€ | 7.20€/kg | 202/17/2/14
- Queso ricotta mezcla Hacendado | 1.60€ | 8.00€/kg | 162/9.7/3.8/12
- Queso brie marcillat de vaca Plaisir de Roy | 1.65€ | 8.25€/kg | 310/27/0.5/22
- Queso fresco de cabra Hacendado | 3.00€ | 12.00€/kg | 262/12.7/3.4/21.9
- Queso azul de vaca Hacendado | 2.30€ | 12.78€/kg | 341/20/0.5/29
- Burrata fresca Hacendado | 2.20€ | 14.67€/kg | 240/13/1.9/20
- Mozzarella fresca di bufala campana Hacendado | 1.85€ | 14.80€/kg | 247/14/0.5/21
- Queso feta mezcla Hacendado en dados | 2.40€ | 16.00€/kg | 277/16/1/23.2

## Queso rallado y lonchas (solo no fundidos)
- Queso rallado emmental gratinar Hacendado | 1.65€ | 8.25€/kg | 369/27/0.5/29
- Queso lonchas tierno de vaca Entrepinares | 2.50€ | 8.33€/kg | 364/21/0.5/31
- Queso lonchas emmental de vaca Hacendado | 2.15€ | 10.75€/kg | 366/27/0.5/29
- Queso lonchas semicurado mezcla Entrepinares | 2.57€ | 12.25€/kg | 394/22/0.5/34
- Queso lonchas de oveja Entrepinares | 2.89€ | 13.75€/kg | 383/21/0.5/33

## Congelados — Verduras y hortalizas (sin salsas)
- Cebolla troceada Hacendado ultracongelada | 0.95€ | 2.11€/kg | 42/1.2/7.9/0.2
- Salteado de verduras Hacendado ultracongelado | 1.55€ | 2.58€/kg | 29/2/3.8/0.3
- Pimiento rojo y verde Hacendado ultracongelado | 1.20€ | 2.67€/kg | 28/0.9/4.5/0.4
- Maíz dulce Hacendado ultracongelado | 1.24€ | 3.10€/kg | 78/2.9/12/1.3
- Migas de coliflor Hacendado ultracongeladas | 1.55€ | 3.44€/kg | 45/2.9/5.6/0.9
- Edamame soja verde Hacendado ultracongelada | 1.75€ | 3.50€/kg | 145/12/3.3/7.6
- Salteado de setas Hacendado ultracongeladas | 1.61€ | 3.58€/kg | 16/1.8/0.5/0.3
- Parrillada de verduras Hacendado ultracongeladas | 1.65€ | 4.12€/kg | 55/2.2/10/0
- Mix frutas tropical Hacendado ultracongeladas | 2.75€ | 6.11€/kg | 59/0.7/12.4/0.2
- Dúo frutas fresa y plátano Hacendado congeladas | 2.75€ | 6.11€/kg | 54/0.9/11.3/0
- Ajo troceado Hacendado ultracongelado | 0.95€ | 6.33€/kg | 148/5.1/24/3.2
- Aguacate en dados Hacendado congelado | 3.50€ | 7.00€/kg | 159/1.6/3/14
- Arándanos enteros Hacendado ultracongelados | 2.15€ | 7.17€/kg | 52/0.7/11/0
- Espárrago verde troceado Hacendado ultracongelado | 2.55€ | 8.50€/kg | 28/2.9/2/0.6

## Congelados — Marisco
- Mejillón de Chile entero cocido Hacendado ultracongelado | 3.25€ | 7.22€/kg | 86/11/7/1.4
- Carne de mejillón de Chile cocido Hacendado ultracongelado | 2.50€ | 9.09€/kg | 95/14/3.2/2.7
- Gambón grande congelado | 23.00€ | 11.50€/kg | 85/18/0/1.5
- Gamba pelada cruda tamaño mediano Hacendado ultracongelada | 5.00€ | 13.89€/kg | 72/14.7/1.9/1
- Gamba pelada cruda tamaño grande Hacendado ultracongelada | 6.35€ | 17.64€/kg | 72/14.7/1/1
- Langostino cocido y pelado Hacendado ultracongelado | 5.00€ | 22.73€/kg | 77/17.2/0.9/0.9
- Camarón boreal cocido y pelado Royal Greenland ultracongelado | 4.75€ | 23.75€/kg | 66/15/0/0.7
- Colas de gambón crudo Hacendado congelado | 6.55€ | 26.20€/kg | 73/16.4/0.5/0.7
- Cigala cruda mediana Hacendado ultracongelada | 9.38€ | 27.60€/kg | 86/18.8/0/0.8

## Congelados — Pescado (sin rebozar)
- Filetes de panga Hacendado ultracongelados | 4.75€ | 5.28€/kg | 72/15.1/0/0.5
- Calamar patagónico pequeño Hacendado ultracongelado | 5.50€ | 11.00€/kg | 78/16.9/0.9/1.6
- Filetes de merluza del Cabo grandes sin piel Hacendado ultracongelados | 11.30€ | 11.65€/kg | 82/18/0.5/1.2
- Tiras de potón del Pacífico Hacendado congeladas | 4.95€ | 12.38€/kg | 77/16/0.5/1.5
- Calamar troceado limpio Hacendado congelado | 6.00€ | 12.63€/kg | 57/12/1/0.5
- Rodajas de atún de aleta amarilla Hacendado congelado | 4.38€ | 17.50€/kg | 91/20/0.5/1
- Porciones de bacalao sin piel MareDeus ultracongeladas | 8.00€ | 20.00€/kg | 52/12.9/0.5/0.5
- Migas de bacalao sin piel MareDeus ultracongeladas | 6.40€ | 21.33€/kg | 57/13/0.5/0.5
- Lomos de salmón sin piel Hacendado congelado | 6.15€ | 24.60€/kg | 222/20/0/16

## Conservas de pescado (al natural o aceite oliva, sin girasol)
- Atún en aceite de oliva Hacendado | 7.70€ | 11.85€/kg | 363/18/0.8/32
- Atún claro en escabeche blanco Hacendado | 4.60€ | 12.78€/kg | 108/17/0.5/4
- Sardinas en aceite de oliva Hacendado | 2.20€ | 13.10€/kg | 289/20/0.7/23
- Sardinillas en aceite de oliva Hacendado | 2.05€ | 15.77€/kg | 366/17/0/33
- Sardinillas reducidas en sal en aceite de oliva Hacendado | 2.05€ | 15.77€/kg | 322/19/0.6/27
- Filetes de caballa del sur en aceite de oliva Hacendado | 2.70€ | 15.88€/kg | 308/18/0.6/26
- Migas de bonito del norte en aceite de oliva Hacendado | 2.90€ | 18.59€/kg | 331/19/0.7/28
- Filetes de caballa contenido reducido en sal en aceite de oliva Hacendado | 3.20€ | 18.82€/kg | 308/18/0.6/26
- Atún claro en aceite de oliva Hacendado | 1.55€ | 18.90€/kg | 357/19/0.9/31
- Bonito del norte en aceite de oliva Hacendado | 3.20€ | 21.92€/kg | 331/19/0.7/28
- Salmón al natural Hacendado | 3.55€ | 23.67€/kg | 129/20/0/5.5
- Filetes de bonito del norte en aceite de oliva Hacendado | 8.10€ | 28.93€/kg | 191/26/0.7/9.3
- Ventresca de atún claro en aceite de oliva Hacendado | 3.30€ | 42.31€/kg | 351/21/0.6/30

## Conservas — Berberechos y mejillones al natural
- Almejones al natural Hacendado | 1.20€ | 19.05€/kg | 73/9.5/4.1/2.1
- Berberecho al natural XS Hacendado | 3.20€ | 35.56€/kg | 53/8.4/4.8/0
- Berberechos al natural S Hacendado | 3.00€ | 47.62€/kg | 53/8.4/4.8/0

## Conservas de verdura
- Judías verdes planas Hacendado | 1.20€ | 3.33€/kg | 17/0.9/3/0
- Judías verdes redondas Hacendado | 1.20€ | 3.33€/kg | 17/0.9/3/0
- Acelgas troceadas Hacendado | 1.80€ | 4.24€/kg | 10/0.7/1.1/0
- Patatas cocidas Hacendado | 1.90€ | 4.75€/kg | 53/1.2/11/0
- Champiñones laminados Hacendado | 1.00€ | 5.56€/kg | 21/2.8/1.5/0.1
- Judías verdes extrafinas Hacendado | 1.90€ | 6.67€/kg | 25/1.8/2.9/0.5
- Pimientos asados en tiras Hacendado | 2.40€ | 8.28€/kg | 30/0.9/5.6/0.5
- Corazones de alcachofa Hacendado | 2.15€ | 8.78€/kg | 26/1.7/3.2/0.4
- Espárragos blancos medianos Hacendado | 1.85€ | 9.03€/kg | 15/1.3/1.6/0.1
- Palmito al natural entero Hacendado | 2.65€ | 10.60€/kg | 20/2/3/0

## Caldos
- Caldo de pollo Hacendado bajo en sal | 1.20€ | 1.20€/L | 42/0.3/0.4/0.8
- Caldo de pescado Hacendado | 1.00€ | 1.00€/L | 7/0.5/0.7/0.2
- Caldo de verduras Hacendado | 1.00€ | 1.00€/L | 34/0.1/0.6/0.6
- Fumet caldo de pescado Hacendado | 3.00€ | 3.16€/kg | 26/0.9/1.3/1.9

## Cremas y gazpachos (los limpios)
- Gazpacho tradicional Hacendado | 1.70€ | 1.70€/L | 40/0.9/3.4/2.6
- Crema de calabaza Hacendado | 1.00€ | 2.00€/L | 36/0.7/4.9/1.3
- Crema de verduras Hacendado | 1.00€ | 2.00€/L | 33/0.5/4.9/1.3
- Crema de calabacín Hacendado | 1.00€ | 2.00€/L | 42/0.8/6.1/1.4
- Salmorejo al estilo cordobés Hacendado | 2.30€ | 2.30€/L | 85/1.1/5.1/6.4

## Tomate
- Tomate triturado Hacendado | 0.60€ | 1.50€/kg | 23/1.1/3.8/0
- Tomate tamizado sin piel Hacendado | 0.90€ | 2.31€/kg | 35/1.4/6.6/0.2

## Fruta y verdura — Ensalada preparada
- Ensalada mezcla 4 estaciones lavada | 0.85€ | 3.40€/kg | 17/0.9/2/0.5
- Lechuga romana cortada y lavada | 1.15€ | 5.75€/kg | 14/1/1.4/0.5
- Ensalada mezcla gourmet maxi lavada | 1.80€ | 6.00€/kg | 21/1.5/2.2/0.5
- Escarola rizada cortada y lavada | 1.25€ | 8.33€/kg | 22/1.2/2.9/0.5
- Canónigos lavados | 1.20€ | 9.60€/kg | 21/1.8/1.6/0.5
- Espinacas baby lavadas | 1.15€ | 11.50€/kg | 22/2.7/1/0.8

## Verdura fresca preparada
- Acelgas cortadas y lavadas | 1.35€ | 4.50€/kg | 25/1.8/3.7/0
- 3 Vegetales para microondas lavados | 1.85€ | 6.17€/kg | 43/2.1/6.7/0.3
- Champiñones laminados limpios | 2.11€ | 6.60€/kg | 20/0.1/2.2/0.6
- Palitos de zanahoria | 2.10€ | 11.67€/kg | 34/0.8/7/0.3
- Mix de setas intenso | 3.76€ | 16.00€/kg | 28/2/3.6/0.5

## Fruta fresca
- Piña natural a rodajas | 3.80€ | 6.55€/kg | 58/0.5/14/0
- Plátano fresco | 1.50€ | 1.50€/kg | 89/1.1/23/0.3
- Manzana fresca | 2.00€ | 2.00€/kg | 52/0.3/14/0.2
- Naranja fresca | 1.50€ | 1.50€/kg | 47/0.9/12/0.1
- Pera fresca | 2.00€ | 2.00€/kg | 57/0.4/15/0.1
- Fresa fresca | 4.00€ | 4.00€/kg | 32/0.7/7.7/0.3
- Kiwi fresco | 3.50€ | 3.50€/kg | 61/1.1/15/0.5
- Aguacate fresco | 5.00€ | 5.00€/kg | 160/2/9/15
- Limón fresco | 2.00€ | 2.00€/kg | 29/1.1/9.3/0.3
- Frutos rojos frescos | 6.00€ | 6.00€/kg | 50/1/10/0.5
- Mango fresco | 4.00€ | 4.00€/kg | 60/0.8/15/0.4
- Uvas frescas | 3.50€ | 3.50€/kg | 69/0.7/18/0.2

## Verdura fresca a peso (frutería Mercadona)
- Tomate fresco | 2.20€ | 2.20€/kg | 18/0.9/3.9/0.2
- Cebolla fresca | 1.20€ | 1.20€/kg | 40/1.1/9.3/0.1
- Ajo fresco | 6.00€ | 6.00€/kg | 149/6.4/33/0.5
- Calabacín fresco | 1.80€ | 1.80€/kg | 17/1.2/3.1/0.3
- Pimiento rojo fresco | 2.50€ | 2.50€/kg | 31/1/6/0.3
- Pimiento verde fresco | 1.80€ | 1.80€/kg | 20/0.9/4.6/0.2
- Berenjena fresca | 2.00€ | 2.00€/kg | 25/1/5.9/0.2
- Zanahoria fresca | 1.00€ | 1.00€/kg | 41/0.9/9.6/0.2
- Champiñón fresco | 4.50€ | 4.50€/kg | 22/3.1/3.3/0.3
- Patata fresca | 1.10€ | 1.10€/kg | 77/2/17/0.1
- Boniato fresco | 2.50€ | 2.50€/kg | 86/1.6/20/0.1
- Puerro fresco | 2.00€ | 2.00€/kg | 61/1.5/14/0.3
- Apio fresco | 2.00€ | 2.00€/kg | 16/0.7/3/0.2
- Espinacas frescas a granel | 3.00€ | 3.00€/kg | 23/2.9/3.6/0.4

## Hierbas frescas
- Perejil fresco | 1.00€ | 10.00€/kg | 36/3/6.3/0.8
- Cilantro fresco | 1.50€ | 15.00€/kg | 23/2.1/3.7/0.5
- Albahaca fresca | 2.50€ | 25.00€/kg | 22/3.2/2.7/0.6
- Menta fresca | 1.50€ | 15.00€/kg | 44/3.3/8.4/0.7

## Huevos
- Huevos grandes L | 1.80€ | 3.60€/dc | 150/12.5/0.5/11
- Huevos de gallinas camperas | 2.10€ | 4.20€/dc | 150/12.5/0.5/11.1
- Huevos super grandes XL | 4.30€ | 4.30€/dc | 150/12.5/0.5/11.1
- Huevos cocidos | 2.20€ | 4.40€/dc | 121/13/0.5/7.7

## Leche y lácteos
- Leche entera fresca Hacendado | 1.15€ | 1.15€/L | 62/3.1/4.5/3.5
- Leche entera Hacendado | 0.96€ | 0.96€/L | 63/3.1/4.6/3.6
- Leche entera sin lactosa Hacendado | 1.03€ | 1.03€/L | 62/3/4.5/3.6

## Bebidas vegetales (sin azúcar)
- Bebida de soja con calcio sin azúcares añadidos Hacendado | 0.65€ | 0.65€/L | 36/3.4/1.2/1.9
- Bebida de avena Hacendado 0% azúcar | 0.75€ | 0.75€/L | 35/0.7/4.7/1.4
- Bebida de almendras con calcio Hacendado | 1.10€ | 1.10€/L | 36/0.7/3.7/2

## Mantequilla y nata (sin margarinas)
- Nata para montar Hacendado | 1.95€ | 3.90€/L | 335/2/3.1/35
- Nata fresca para cocinar Hacendado | 1.30€ | 6.60€/kg | 284/2.4/1.9/30
- Mantequilla con sal Hacendado | 2.10€ | 8.40€/kg | 734/0.5/0.8/81
- Mantequilla sin sal añadida Hacendado | 2.10€ | 8.40€/kg | 743/0.5/0.8/82

## Marisco fresco
- Langostino cocido | 6.30€ | 10.50€/kg | 103/22.2/0/1.6
- Gamba cocida | 6.95€ | 23.17€/kg | 102/22.8/0.5/1

## Pescado fresco
- Filetes de Gallineta descongelada | 6.08€ | 16.00€/kg | 81/16/0.5/1.8
- Calamar pequeño limpio patagónico | 6.00€ | 20.00€/kg | 62/12/0/1.5
- Bacalao al punto de sal descongelado | 9.50€ | 21.10€/kg | 63/15.8/0.5/0.5
- Rodajas de atún de aleta amarilla | 5.37€ | 22.85€/kg | 91/20/0.5/1
- Patas de pulpo cocido | 10.50€ | 42.00€/kg | 70/16/0/0.7

## Salazones y ahumados (con aceite de oliva)
- Boquerones en vinagre Hacendado en aceite de girasol | 1.65€ | 27.50€/kg | 203/19.4/0.8/13.6
- Migas de bacalao desaladas Hacendado | 7.27€ | 25.50€/kg | 60/14.1/0/0.4
- Filetes de anchoa en aceite de oliva Hacendado | 2.80€ | 32.18€/kg | 280/26/0.5/20
- Taquitos de salmón ahumado Hacendado | 3.80€ | 38.00€/kg | 171/22/0.5/9.1

## Harina (básicas, sin preparados)
- Harina integral de trigo Hacendado | 0.90€ | 0.90€/kg | 328/12/60/2
- Harina de trigo Hacendado | 0.72€ | 0.72€/kg | 344/10/72/1.4
- Harina de garbanzo Hacendado | 2.00€ | 4.00€/kg | 342/20.2/57/6.5
- Harina de maíz blanco precocida Hacendado | 1.60€ | 1.60€/kg | 357/9.2/75/1.9

## Pan de horno (integrales y masa madre)
- 5 Barras de pan 51% integral | 1.35€ | 2.16€/kg | 239/10/43/3.2
- Baguette masa madre | 0.57€ | 2.28€/kg | 258/8.5/55/1
- 6 Panes de centeno 51% | 1.47€ | 3.16€/kg | 262/9.4/50/1.7
- 6 Panecillos integrales 100% | 1.05€ | 3.89€/kg | 238/9.2/42.6/1.5
- Barra de pan campesina masa madre | 0.65€ | 2.60€/kg | 268/8.9/54.3/1
- Panes integrales 100% fino | 1.40€ | 8.48€/kg | 223/9.1/38/2.5

## Pan de molde (integrales)
- Pan de molde 100% integral familiar Hacendado | 1.15€ | 1.40€/kg | 248/8.7/41/3.8
- Pan de molde 12 cereales y semillas Hacendado | 1.61€ | 2.37€/kg | 259/11/38/5.7
- Pan de molde con 35% avena 0% azúcares añadidos 100% integral Hacendado | 1.37€ | 2.98€/kg | 265/13/35/6.8
- Pan de molde espelta 100% integral Hacendado natural | 1.65€ | 3.00€/kg | 240/12/35/4.1

## Pan tostado (integrales)
- Pan tostado 100% integral | 1.80€ | 3.27€/kg | 376/16/69/11.5
- Pan tostado 100% integral bajo en sal y en azúcares Hacendado | 2.17€ | 4.02€/kg | 388/18/61/5.7
- Pan tostado 100% espelta integral Hacendado | 1.47€ | 5.88€/kg | 382/17/59/6.4
- Panecillo tostado 100% integral de trigo Hacendado | 1.13€ | 3.77€/kg | 382/13.3/59.6/7.8
- Pan de fibra y sésamo Hacendado | 1.13€ | 4.52€/kg | 391/13/60.1/7.6

## Hummus (receta clásica sin aditivos)
- Hummus de garbanzos Hacendado receta clásica | 1.05€ | 4.38€/kg | 311/6/11.1/25.8
- Hummus de garbanzos con pimiento del piquillo asado Hacendado | 1.45€ | 6.04€/kg | 313/5.7/10.7/26

## Yogures naturales y kéfir
- Yogur natural Hacendado 0% MG 0% azúcares añadidos | 1.05€ | 1.40€/kg | 36/4.3/4.5/0.1
- Postre lácteo cremoso natural edulcorado Hacendado 0% MG 0% azúcares añadidos | 1.40€ | 1.87€/kg | 42/4.9/5.6/0
- Postre lácteo natural +Proteínas Hacendado 0% MG 10 g proteínas | 1.40€ | 2.80€/kg | 52/10/3.1/0.5
- Yogur natural Hacendado | 1.00€ | 1.33€/kg | 58/3.7/4.1/3.4
- Yogur natural Danone | 1.70€ | 1.77€/kg | 63/3.5/9.5/1.5
- Kéfir natural sabor suave | 1.10€ | 2.20€/kg | 74/3.9/5.1/4.2
- Yogur natural de cabra Hacendado | 2.10€ | 4.20€/kg | 73/4.1/3/4.9
- Bebida Kéfir natural Hacendado 0% MG | 0.90€ | 3.60€/kg | 36/3.9/4.8/0.5

## Yogur griego natural (sin sabores ni azúcar)
- Yogur griego natural Hacendado | 1.45€ | 1.93€/kg | 129/3.9/3.9/10.8
- Yogur griego natural Hacendado familiar | 2.20€ | 2.20€/kg | 129/3.9/3.9/10.8
- Yogur griego natural ligero Hacendado 2% MG | 2.20€ | 2.20€/kg | 60/5.8/4.7/2

## Bífidus naturales (sin azúcar)
- Bífidus desnatado probióticos natural Hacendado 0% MG 0% azúcares añadidos | 1.15€ | 1.53€/kg | 41/4.6/5.5/0.1
- Bífidus probióticos natural Hacendado | 1.20€ | 1.60€/kg | 70/3.8/4.4/4.2
- Bífidus cremoso desnatado probióticos natural edulcorado Hacendado 0% MG 0% azúcares añadidos | 1.40€ | 1.87€/kg | 51/5.4/6.6/0.3

## Batidos lácteos proteicos (solo los útiles)
- Batido lácteo sabor vainilla +Proteínas Hacendado 30 g proteínas | 1.30€ | 3.94€/L | 46/9.1/2/0.2
- Batido lácteo sabor chocolate +Proteínas Hacendado 30 g proteínas | 1.30€ | 3.94€/L | 48/9.1/2.2/0.3
- Batido lácteo sabor café +Proteínas Hacendado 30 g proteínas | 1.40€ | 4.24€/L | 46/9.1/2/0.2

## Zumos (solo 100% exprimidos)
- Zumo pura naranja Hacendado | 1.85€ | 1.85€/L | 44/0.7/9.9/0.1
- Zumo pura naranja con pulpa Hacendado | 1.90€ | 1.90€/L | 44/0.7/9.9/0.1
- Zumo de naranja recién exprimido Hacendado | 1.95€ | 7.80€/L | 46/0.7/10.5/0.2
- Zumo de tomate Hacendado | 1.05€ | 1.05€/L | 18/0.9/3.3/0
`
